# Generated by Django 5.0.6 on 2025-08-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('payload', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=200)),
                ('registration_date', models.DateField()),
                ('joining_date', models.DateField()),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_fee_paid', models.BooleanField(default=False)),
                ('total_due_months', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='fees.student')),
            ],
        ),
    ]
