# Generated by Django 5.1.4 on 2025-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdue',
            name='collected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdue',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
