# Generated by Django 5.1.4 on 2025-08-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_studentdue_collected_by_studentdue_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdue',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='studentdue',
            name='payment_method',
        ),
    ]
