# Generated by Django 5.1.4 on 2025-08-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_remove_studentdue_collected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdue',
            name='collected_by',
            field=models.CharField(blank=True, choices=[('Sangamesh', 'Sangamesh'), ('Sridhar', 'Sridhar'), ('Binduja', 'Binduja')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentdue',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('GPay', 'GPay'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdue',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
