# Generated by Django 5.0.6 on 2026-07-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_studentdue_collected_by_studentdue_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdue',
            name='collected_by',
            field=models.CharField(blank=True, choices=[('Sangamesh', 'Sangamesh'), ('Ashwath', 'Ashwath'), ('Binduja', 'Binduja')], max_length=50, null=True),
        ),
    ]
